chat/urls.py
from django.urls import path
from .views import chat_page, display_all_user_messages

app_name = 'chat'

urlpatterns = [
    path('message/<int:id>/', chat_page, name='message'),
    path('messages/', display_all_user_messages, name='messages')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"),
    path("posts/", include('posts.urls', namespace='posts')),
    path('profile/', include('user.urls', namespace='profiles')),
    path('chat/', include('chat.urls', namespace='chat'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from .views import (profile, create_profile, login_user, signup, logout_user,
                    ProfileDetailView, search_user,
                    profiles_to_add_friend, ProfileListView,
                    send_friend_request, remove_friend, cancel_friend_request,
                    ViewFriendList, FriendRequestReceivedView, accept_friend_request)


app_name = 'profiles'

urlpatterns = [
    path("", profile, name='profile'),
    path("add-profile", create_profile, name="create_profile"),
    path("login", login_user, name='login'),
    path('signup', signup, name='signup'),
    path("logout", logout_user, name='logout'),
    path("<int:pk>/profile", ProfileDetailView.as_view(), name="profile-detail"),
    path('search', search_user, name='search-user'),
    path('add-friend', profiles_to_add_friend, name='add-friend'),
    path('peoples', ProfileListView.as_view(), name='peoples'),
    path('add-friend/<int:user_id>', send_friend_request, name='add-friend'),
    path('remove-friend/<int:user_id>', remove_friend, name='remove-friend'),
    path('cancel-friend/<int:user_id>',
         cancel_friend_request, name='cancel-request'),
    path('friends', ViewFriendList.as_view(), name='friends'),
    path('requests', FriendRequestReceivedView.as_view(), name='friend-request'),
    path('accept_request/<int:profile_id>',
         accept_friend_request, name='accept-friend')

]

user/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from datetime import datetime
from abstract.abstract import BaseModel
from django.db.models import Q

STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class ProfileManager(models.Manager):
    def get_all_profiles(self, me):
        qs = Profile.objects.exclude(user=me).all()
        return qs

    def get_all_profiles_to_add(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(
            Q(sender=profile) | Q(receiver=profile))

        accepted_profile = []
        for relation in qs:
            if relation.status == 'accepted':
                accepted_profile.append(relation.sender)
                accepted_profile.append(relation.receiver)

        available_profile = [
            profile for profile in profiles if profile not in accepted_profile]

        return available_profile

    def friends_list(self, user):
        profile = Profile.objects.get(user=user)
        friends = profile.friends.all()

        friends_profile = []
        for user_ in friends:
            profile_ = Profile.objects.get(user=user_)
            friends_profile.append(profile_)
        return friends_profile


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    address = models.CharField(max_length=100)
    bio = models.TextField(max_length=200, default="no bio")
    friends = models.ManyToManyField(User, related_name='friends', blank=True)
    profile_pic = models.ImageField(upload_to='profile', default='avatar.png', validators=[
                                    FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    objects = ProfileManager()

    def full_name(self):
        return self.first_name + " " + self.last_name

    def email(self):
        return self.user.email

    def post_count(self):
        return self.posts.count()

    class Meta:
        ordering = ('-updated',)

    def __str__(self) -> str:
        return f"{self.user.username} has created profile on {datetime.strftime(self.updated, '%a,%d %b, %Y %I:%M:%S %p')}"


class RelationshipManager(models.Manager):
    def invitation_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status="send")
        profiles = []
        if qs:

            for relation in qs:
                profiles.append(relation.sender)

        return profiles


class Relationship(BaseModel):
    sender = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)

    objects = RelationshipManager()

    def __str__(self) -> str:
        return f"{self.sender.user.username} send friend request to {self.receiver.user.username}"

user/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name',
                  'address', 'bio', 'profile_pic')


class LoginForm(forms.Form):
    username = forms.CharField(label="username", max_length=100)
    password = forms.CharField(
        label="password", max_length=200, widget=forms.PasswordInput())


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, LoginForm, SignUpForm
from .models import Profile, Relationship
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib import messages


@login_required(login_url='/profile/login')
def profile(request):
    profile_ = Profile.objects.get(user=request.user)
    update_form = UserUpdateForm(instance=profile_)
    return render(request, 'profile.html', {'form': update_form, 'profile': profile_})


@login_required(login_url='/profile/login')
def create_profile(request):
    form = UserUpdateForm()
    profile_ = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = UserUpdateForm(request.POST, request.FILES, instance=profile_)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect("/profile")
    return render(request, 'add-user.html', {'form': form, 'profile': profile_})


def login_user(request):
    if (request.user.is_authenticated):
        return redirect("/")
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect("/")
            messages.error(
                request, 'Invalid username or password. Try Again ...')
    return render(request, 'login.html', {'form': form})


def signup(request):
    if (request.user.is_authenticated):
        return redirect("/")
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/profile/login")
    return render(request, 'signup.html', {'form': form})


@login_required(login_url='/profile/login')
def logout_user(request):
    logout(request)
    return redirect("/profile/login")


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    pk_url_kwarg = 'pk'
    template_name = 'profile.html'


@login_required(login_url='/profile/login')
def search_user(request):
    try:
        users = User.objects.get(username=request.POST.get('username'))
        profile = Profile.objects.filter(user=users).exclude(request.user)
        # profile_ = Profile.objects.get(user=request.user)
        context = {
            'object_list': profile,
            # 'profile': profile_
        }
        return render(request, 'people-list.html', context)
    except:
        message = {'message': 'User Doesnot exist'}
        return render(request, 'people-list.html', context=message)


class FriendRequestReceivedView(ListView):
    model = Profile
    template_name = 'friends.html'

    def get_queryset(self):
        profile = Profile.objects.get(user=self.request.user)
        qs = Relationship.objects.invitation_received(receiver=profile)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        context['profile'] = profile

        relation_receiver = Relationship.objects.filter(receiver=profile)

        rel_receiver = []
        for profile_ in relation_receiver:
            rel_receiver.append(profile_.receiver.user)
            print('receiver -> ', profile_.receiver.user)

        context['receiver'] = rel_receiver
        request_available = Relationship.objects.filter(
            Q(receiver=profile) & Q(status="send"))

        context['request_count'] = len(request_available)

        return context


@login_required(login_url='/profile/login')
def profiles_to_add_friend(request):
    profiles = Profile.objects.get_all_profiles_to_add(request.user)
    context = {
        'profiles': profiles
    }
    return render(request, 'to-add-friend.html', context)


@login_required(login_url='/profile/login')
def get_all_user(request):
    profile_ = Profile.objects.get(user=request.user)
    profiles = Profile.objects.get_all_profiles(request.user)
    context = {
        'profiles': profiles,
        'profile': profile_
    }
    return render(request, 'people-list.html', context)


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'people-list.html'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        context['profile'] = profile

        relation_receiver = Relationship.objects.filter(sender=profile)
        relation_sender = Relationship.objects.filter(receiver=profile)

        rel_sender = []
        rel_receiver = []
        for profile_ in relation_receiver:
            rel_receiver.append(profile_.receiver.user)

        for profile_ in relation_sender:
            rel_sender.append(profile_.sender.user)

        context['sender'] = rel_sender
        context['receiver'] = rel_receiver
        request_available = Relationship.objects.filter(
            Q(receiver=profile) & Q(status="send"))
        context['request_count'] = len(request_available)

        return context


@login_required(login_url='/profile/login')
def send_friend_request(request, user_id):
    sender = Profile.objects.get(user=request.user)
    receiver = Profile.objects.get(id=user_id)
    Relationship.objects.create(
        sender=sender, receiver=receiver, status='send')
    return redirect("/profile/peoples")


@login_required(login_url='/profile/login')
def remove_friend(request, user_id):
    sender = Profile.objects.get(user=request.user)
    receiver = Profile.objects.get(id=user_id)
    rel = Relationship.objects.get((Q(sender=sender) & Q(receiver=receiver)) | (
        Q(sender=receiver) & Q(receiver=sender)))
    rel.delete()
    return redirect('/profile/peoples')


@login_required(login_url='/profile/login')
def cancel_friend_request(request, user_id):
    sender = Profile.objects.get(user=request.user)
    receiver = Profile.objects.get(id=user_id)
    rel = Relationship.objects.get((Q(sender=sender) & Q(receiver=receiver)) | (
        Q(sender=receiver) & Q(receiver=sender)))
    rel.delete()
    return redirect('/profile/peoples')


class ViewFriendList(ListView):
    model = Profile
    template_name = 'people-list.html'

    def get_queryset(self):
        qs = Profile.objects.friends_list(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        context['profile'] = profile
        request_available = Relationship.objects.filter(
            Q(receiver=profile) & Q(status="send"))
        context['request_count'] = len(request_available)
        return context


def accept_friend_request(request, profile_id):
    receiver = Profile.objects.get(user=request.user)
    sender = Profile.objects.get(id=profile_id)
    relationship = Relationship.objects.get(
        Q(sender=sender) & Q(receiver=receiver))
    relationship.status = 'accepted'
    relationship.save()
    return redirect('/profile/friends')

user/templates/add-user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary">Create Profile</button>
</form>
{% endblock content %}

</form>

user/templates/friend-request.html
{% extends "base.html" %}

{% block content %}
{% for request in requests%}
{{request}}
{%endfor%}

{% endblock content %}

user/templates/friends.html
{% extends "base.html" %}

{% block content %}
{% for profile in object_list  %}
<div class="d-flex flex-start p-2 ms-4">
    <img class="rounded-circle shadow-1-strong me-3" src="{{profile.profile_pic.url}}" alt="avatar" width="80"
        height="80" />
    <div>
        <a href="{% url 'profiles:profile-detail' profile.id %}" style="text-decoration: none; color: black;">
            <h6 class="fw-bold mb-1 mt-4">{{profile.user.username}}</h6>
        </a>
        <a class="btn btn-secondary" href="{% url 'profiles:profile-detail' profile.id %}" role="button">View
            Profile</a>


        {% if request.user in receiver and request.user not in profile.friends.all %}
        <a class="btn btn-danger" href="{% url 'profiles:accept-friend' profile.id%}" role="button">Accept Request</a>
        {% endif %}

    </div>
</div>
{% endfor %}
{% endblock %}

user/templates/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h2 class="m-4" style="text-align: center;">Login</h2>
<hr />
<div class="row d-flex align-items-center justify-content-center">
    <div class="col-lg-4">
        <div class="card mb-4">
            {% for message in messages %}

            <div class="alert alert-danger">
                {{ message }}
            </div>

            {% endfor %}
            <form class="m-3" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    <button class="btn btn-primary">Login</button>
                </div>

            </form>
            <div class="m-4">
                <p>Already have an account? <a href="{% url 'profiles:signup'%}">Signup</a></p>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

</form>

user/templates/people-list.html
{% extends "base.html" %}

{% block content %}
{% if message %}
<span style="text-align: center; color: red;">{{message}}</span>
{% endif %}

{% for profile in object_list  %}
<div class="d-flex flex-start p-2 ms-4">
    <img class="rounded-circle shadow-1-strong me-3" src="{{profile.profile_pic.url}}" alt="avatar" width="80"
        height="80" />
    <div>
        <a href="{% url 'profiles:profile-detail' profile.id %}" style="text-decoration: none; color: black;">
            <h6 class="fw-bold mb-1 mt-4">{{profile.user.username}}</h6>
        </a>
        <a class="btn btn-secondary" href="{% url 'profiles:profile-detail' profile.id %}" role="button">View
            Profile</a>
        {% if profile.user not in receiver and profile.user not in sender %}
        <a class="btn btn-primary" href="{% url 'profiles:add-friend' profile.id%}" role="button">Add Friend</a>
        {% endif %}
        {% if profile.user in receiver and request.user not in profile.friends.all %}
        <a class="btn btn-outline-danger" href="{% url 'profiles:cancel-request' profile.id%}" role="button">Cancel
            Request</a>
        {% endif %}

        {% if request.user in profile.friends.all %}
        <a class="btn btn-danger" href="{% url 'profiles:remove-friend' profile.id%}" role="button">Remove Friend</a>
        <a class="btn btn-primary" href="{% url 'chat:message' profile.id%}" role="button">Message</a>
        {% endif %}

    </div>
</div>
{% endfor %}
{% endblock %}

user/templates/profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
{% if request.user == profile.user%}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Update Profile</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data" action="{%url 'profiles:create_profile'%}">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
{% endif %}
<!-- end of modal  -->
<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <img src="{{profile.profile_pic.url}}" alt="avatar" class="rounded-circle img-fluid"
                            style="width: 150px;">
                        <h5 class="my-3">{{profile.full_name}}</h5>
                        <p class="text-muted mb-1">{{profile.bio}}</p>
                        <p class="text-muted mb-4">{{profile.address}}</p>
                        <div class="d-flex justify-content-center mb-2">
                            <!-- <button type="button" class="btn btn-primary">Add Friend</button> -->
                            {% if request.user == profile.user%}
                            <button type="button" class="btn btn-outline-primary ms-1" data-bs-toggle="modal"
                                data-bs-target="#exampleModal">
                                Update Profile
                            </button>
                            {%endif%}
                        </div>
                        <!-- <button type="button" class="btn btn-secondary">View Friends</button> -->
                    </div>
                </div>
                <div class="card mb-4 mb-lg-0">
                    <div class="card-body p-0">
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Full Name</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{profile.full_name}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Email</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{profile.email}}</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Address</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{profile.address}}</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Number of Post</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{profile.post_count}}</p>
                            </div>
                        </div>

                        <hr>
                        <!-- <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Number of Friends</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{profile.address}}</p>
                            </div> -->
                        <!-- </div> -->

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

{% endblock content %}

user/templates/signup.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h2 class="m-4" style="text-align: center;">Create Account</h2>
<hr />
<div class="row d-flex align-items-center justify-content-center">
    <div class="col-lg-6">
        <div class="card mb-8">
            <form class="m-3" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-primary">Signup</button>
            </form>
            <div class="m-4">
                <p>Already have an account? <a href="{% url 'profiles:login'%}">Login</a></p>
            </div>
        </div>


    </div>

</div>

{% endblock content %}

</form>

user/templates/to-add-friend.html
{% extends "base.html" %}

{% block content %}
{% for profile in profiles  %}
<div class="d-flex flex-start p-2">
    <img class="rounded-circle shadow-1-strong me-3" src="{{profile.profile_pic.url}}" alt="avatar" width="60"
        height="60" />
    <div>
        <a href="{% url 'profiles:profile-detail' profile.id %}" style="text-decoration: none; color: black;">
            <h6 class="fw-bold mb-1 mt-4">{{profile.user.username}}</h6>
        </a>
    </div>
</div>
{% endfor %}
{% endblock %}