chat/urls.py
from django.urls import path
from .views import chat_page, display_all_user_messages

app_name = 'chat'

urlpatterns = [
    path('message/<int:id>/', chat_page, name='message'),
    path('messages/', display_all_user_messages, name='messages')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"),
    path("posts/", include('posts.urls', namespace='posts')),
    path('profile/', include('user.urls', namespace='profiles')),
    path('chat/', include('chat.urls', namespace='chat'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import add_new_post, delete_post, update_post, add_comment
app_name = "posts"

urlpatterns = [
    path("add-post", add_new_post, name="new-post"),
    path("delete/<int:post_id>", delete_post, name="delete-post"),
    path("update/<int:post_id>", update_post, name="update-post"),
    path('add-comment/', add_comment, name="add-comment")
]

user/urls.py
from django.urls import path
from .views import (profile, create_profile, login_user, signup, logout_user,
                    ProfileDetailView, search_user,
                    profiles_to_add_friend, ProfileListView,
                    send_friend_request, remove_friend, cancel_friend_request,
                    ViewFriendList, FriendRequestReceivedView, accept_friend_request)


app_name = 'profiles'

urlpatterns = [
    path("", profile, name='profile'),
    path("add-profile", create_profile, name="create_profile"),
    path("login", login_user, name='login'),
    path('signup', signup, name='signup'),
    path("logout", logout_user, name='logout'),
    path("<int:pk>/profile", ProfileDetailView.as_view(), name="profile-detail"),
    path('search', search_user, name='search-user'),
    path('add-friend', profiles_to_add_friend, name='add-friend'),
    path('peoples', ProfileListView.as_view(), name='peoples'),
    path('add-friend/<int:user_id>', send_friend_request, name='add-friend'),
    path('remove-friend/<int:user_id>', remove_friend, name='remove-friend'),
    path('cancel-friend/<int:user_id>',
         cancel_friend_request, name='cancel-request'),
    path('friends', ViewFriendList.as_view(), name='friends'),
    path('requests', FriendRequestReceivedView.as_view(), name='friend-request'),
    path('accept_request/<int:profile_id>',
         accept_friend_request, name='accept-friend')

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Social Connect</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.png'%}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>

    <body>
        <nav>
            {% include "navbar.html" %}
        </nav>
        <main>
            {%block content%}
            {%endblock%}
        </main>
        <footer>
            <hr className="mt-5" />
            <footer style="text-align: center;">Social Connect &copy; Copyright 2023. All Rights Reserved.</footer>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
        </script>
    </body>

</html>

templates/homepage.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% block content %}

<div class="row">
    <div class="col-lg-8 border border-primary">
        <section>
            <div class="container my-3 py-2">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-12 col-lg-10">
                        <div class="card text-dark">
                            <div class="card-body p-4">
                                <h4 class="mb-0">Recent Posts</h4>
                                <p class="fw-light mb-4 pb-2">Latest Posts section by users</p>
                                {% for post in posts %}
                                <div class="d-flex flex-start p-2">
                                    <img class="rounded-circle shadow-1-strong me-3"
                                        src="{{post.author.profile_pic.url}}" alt="avatar" width="60" height="60" />
                                    <div>
                                        <h6 class="fw-bold mb-1">{{post.author.user.username}}</h6>
                                        <div class="d-flex align-items-center mb-3">
                                            <p class="mb-0">
                                                {{post.updated | timesince}} ago
                                            </p>
                                            {% if request.user == post.author.user%}
                                            <div class="ms-5">
                                                <a href="{% url 'posts:delete-post' post.id %}"
                                                    class="btn btn-danger btn-sm" role="button"
                                                    aria-disabled="true">{% bs_icon 'trash' %}</a>
                                                <a href="{% url 'posts:update-post' post.id %}"
                                                    class="btn btn-secondary btn-sm" role="button"
                                                    aria-disabled="true">{% bs_icon 'pencil' %}</a>


                                            </div>
                                            {% endif %}
                                        </div>

                                        <p class="mb-0">
                                            {{post.content}}
                                        </p>
                                        {% if post.image %}
                                        <img src="{{post.image.url}}" alt="post image" width="200" height="200" />
                                        {% endif %}
                                    </div>

                                </div>


                                <p> Comments ({{post.get_comments_count}}) </p>


                                <form class="mb-4" method="post" action="{% url 'posts:add-comment'%}">
                                    {% csrf_token %}
                                    {% bootstrap_form c_form %}
                                    <input type="hidden" name="post_id" value="{{post.id}}" />
                                    <button class="btn btn-primary">comment</button>
                                </form>
                                {% for comment in post.get_all_comments%}
                                <!-- <p>{{comment.comment}}</p> -->
                                <div class="d-flex flex-start p-2">
                                    <img class="rounded-circle shadow-1-strong me-3"
                                        src="{{comment.user.profile_pic.url}}" alt="avatar" width="30" height="30" />
                                    <div>
                                        <h6 class="fw-bold mb-1 mt-2">{{comment.user.user.username}}</h6>
                                        <span>{{comment.updated | timesince}} ago</span>
                                        <p>{{comment.comment}}</p>
                                    </div>
                                    <hr />
                                </div>
                                {%endfor%}
                                {% endfor %}
                            </div>

                            <hr class="my-0" style="height: 1px;" />
                        </div>
                    </div>
                </div>
        </section>
    </div>
    <div class="col-lg-4 my-3">
        <h3>Add New Post</h3>
        <hr />
        <form method="post" action="{% url 'posts:new-post'%}" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form post_form %}
            <button class="btn btn-primary">Add New Post</button>
        </form>
    </div>

</div>

{% endblock content %}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage'%}">
            <img src="{% static 'images/social-connect.png'%}" alt="Social Connect" width="90" height="90">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                <li>
                    <form class="d-flex" role="search" method="post" action="{% url 'profiles:search-user'%}">
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" name="username" placeholder="Search"
                            aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </li>
                <!-- <li>
                    <a href="{% url 'profiles:peoples' %}" class="btn btn-secondary ms-5" role="button"
                        aria-disabled="true">Peoples</a>
                </li> -->
                <!-- <li>


                </li> -->
                <!-- <li>
                    <a href="{% url 'profiles:friend-request' %}" class="btn btn-secondary ms-5" role="button"
                        aria-disabled="true">Requests({{request_count}})</a>
                </li> -->
                {%endif%}
            </ul>
            <div class="d-flex">
                {% if request.user.is_authenticated %}
                <a href="{% url 'profiles:friends' %}" class="me-5" aria-disabled="true"><i class="bi bi-people-fill"
                        style="color: white;font-size: 2rem;"></i></a>
                <a href="{% url 'chat:messages' %}" class="me-5" aria-disabled="true"><i class="bi bi-chat-left"
                        style="color: white;font-size: 2rem;"></i></a>
                <a class=" navbar-brand" href="{% url 'profiles:profile'%}">
                    <img src="{{profile_pic.url}}" alt="{{request.user.username}}" width="30" class="rounded-pill">
                    <span>{{request.user.username}}</span>
                </a>
                <a href="{% url 'profiles:logout'%}" class="btn btn-danger ms-5" role="button"
                    aria-disabled="true">Logout</a>
                {%else%}
                <!-- <a href="{% url 'profiles:login'%}" class="btn btn-primary me-4" role="button"
                    aria-disabled="true">Login</a> -->
                {%endif%}
            </div>
        </div>
    </div>
</nav>